### PR TITLE
Added sharkpools extensions to the whitelist.

### PR DESCRIPTION
**Pull request by hammouda101010**
# Changes
Some Extensions from Sharkpool (Including Legacy Ones) were added to whitelist.

### CODE REVIEW

**Comment by hammouda101010** [comment]
this may never be approved i guess

**Comment by JeremyGamer13** [comment]
this is the old api repo

**Comment by JeremyGamer13** [comment]
new one is https://github.com/PenguinMod/PenguinMod-BackendApi

**Comment by JeremyGamer13** [comment]
actually we should probably archive this repo

**Pull request closed without merging**
